version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfile.frontend
      target: build
    command: npm start
    ports:
      - 52525:52525
    environment:
      - DEV_BACKEND_URL=http://backend:52526

  backend:
    build:
      context: .
      dockerfile: ./dockerfile.backend
    ports:
      - 52526:52526
    environment:
      - PORT=52526
