version: 2

jobs:
  build:frontend:
    docker:
      - image: circleci/node
    steps:
      # Enable Docker environment
      - setup_remote_docker
      # Fetch the source code
      - checkout
      # Log in to Docker Hub
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      # Build the image, tagging it as latest
      - run: docker build -t shabados/database-viewer-frontend:${CIRCLE_SHA1} frontend
      # Push the image to Docker Hub
      - run: docker push shabados/database-viewer-frontend:${CIRCLE_SHA1}

  build:backend:
    docker:
      - image: circleci/node
    steps:
      # Enable Docker environment
      - setup_remote_docker
      # Fetch the source code
      - checkout
      # Log in to Docker Hub
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      # Build the image, tagging it as latest
      - run: docker build -t shabados/database-viewer-backend:${CIRCLE_SHA1} backend
      # Push the image to Docker Hub
      - run: docker push shabados/database-viewer-backend:${CIRCLE_SHA1}

workflows:
  version: 2
  build:
    jobs:
      - build:backend:
          filters:
            branches:
              only: master
      - build:frontend:
          filters:
            branches:
              only: master
