name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - integration

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - run: npm ci

      - run: npm run lint

  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: shabados/actions/setup-git-identity@release/next
        with:
          user: Shabad OS Bot
          email: team@shabados.com

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - run: npm ci

      - run: npm run test

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Video
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        context: [frontend, backend]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: dockerfile.${{ matrix.context }}
