name: Release

on: workflow_dispatch

jobs:
  publish:
    name: Build and Push (Github)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub 
      run: echo ${{ secrets.DOCKERHUB_BOT_TOKEN }} | docker login --username shabados --password-stdin

    - name: Build Docker Image Backend
      run: docker build -f ./backend/Dockerfile -t shabados/database-viewer-backend:${GITHUB_SHA} .

    - name: Build Docker Image Frontend
      run: docker build -f ./frontend/Dockerfile -t shabados/database-viewer-frontend:${GITHUB_SHA} .

    - name: Publish to Docker Hub
      run: |
        docker push shabados/database-viewer-frontend:${GITHUB_SHA}
        docker push shabados/database-viewer-backend:${GITHUB_SHA}
