name: Release Next

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: release

jobs:
  release:
    uses: shabados/actions/.github/workflows/release.yml@main
    with:
      prerelease: true
    secrets:
      GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
